### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#54]
Event code: 3005 
Event message: An unhandled exception has occurred. 
 
Exception information: 
    Exception type: NullReferenceException 
    Exception message: Object reference not set to an instance of an object.
   at System.Data.Linq.SqlClient.QueryConverter.VisitInvocation(InvocationExpression invoke)
   at System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   at System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   at System.Data.Linq.SqlClient.QueryConverter.VisitBinary(BinaryExpression b)
   at System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   at System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   at System.Data.Linq.SqlClient.QueryConverter.VisitFirst(Expression sequence, LambdaExpression lambda, Boolean isFirst)
   at System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   at System.Data.Linq.SqlClient.QueryConverter.ConvertOuter(Expression node)
   at System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNodeAnnotations annotations)
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at System.Data.Linq.Table`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at ProStudCreator.ShibUser.GetDepartment(String orgUnitDn)
   at ProStudCreator.ShibUser.GetDepartmentId()
   at ProStudCreator.ShibUser.IsAuthenticated()
   at ProStudCreator.SiteMaster.master_Page_PreLoad(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.UI.Page.OnPreLoad(EventArgs e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

 
 
Request information: 
    Request URL: http://server1085.cs.technik.fhnw.ch/prostud/projectlist.aspx 
    Request path: /prostud/projectlist.aspx 
    User host address: 147.86.8.115 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\DefaultAppPool 
 
Thread information: 
    Thread ID: 15 
    Thread account name: IIS APPPOOL\DefaultAppPool 
    Is impersonating: False 
    Stack trace:    at System.Data.Linq.SqlClient.QueryConverter.VisitInvocation(InvocationExpression invoke)
   at System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   at System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   at System.Data.Linq.SqlClient.QueryConverter.VisitBinary(BinaryExpression b)
   at System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   at System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   at System.Data.Linq.SqlClient.QueryConverter.VisitFirst(Expression sequence, LambdaExpression lambda, Boolean isFirst)
   at System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   at System.Data.Linq.SqlClient.QueryConverter.ConvertOuter(Expression node)
   at System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNodeAnnotations annotations)
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at System.Data.Linq.Table`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at ProStudCreator.ShibUser.GetDepartment(String orgUnitDn)
   at ProStudCreator.ShibUser.GetDepartmentId()
   at ProStudCreator.ShibUser.IsAuthenticated()
   at ProStudCreator.SiteMaster.master_Page_PreLoad(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.UI.Page.OnPreLoad(EventArgs e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by StephenRUK** [comment]
Das AD-Konto von Norbert Seyff ist nicht in der i4Ds Organisational Unit, sondern im Studiengang Informatik 62_I. Zudem hat er keinen Eintrag in der Mapping-Tabelle, weswegen die Anmeldung nicht gelang.

Allerdings sollte dies nicht zu einer NullReferenceException führen, sondern zur 403 Forbidden Custom Error Page.

**Comment by StephenRUK** [comment]
Ein fehlender Null-Check wurde nun ergänzt, der zu einem Fehler führte wenn kein Mapping-Eintrag vorhanden war. Somit sollte die korrekte 403-Seite angezeigt werden.

Norbert Seyff ist nun ebenfalls im Mapping erfasst.
